# Use postgres/example user/password credentials
version: '3.1'

services:

  # db:
  #   image: postgres:16.0
  #   volumes:
  #     - ./postgres/install.sh:/docker-entrypoint-initdb.d/install.sh
  #     - ./files/:/files/
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example

  jupyter:
    build: ./jupyter_docker
    volumes:
      - ./notebooks/:/home
    ports:
      - 8888:8888
    working_dir: /home

  rumble:
    build: ./rumble_docker
    volumes:
      - ./notebooks/:/home
      - ./rumble_docker/rumbledb-1.21.0-standalone.jar:/rumbledb-1.21.0-standalone.jar
    ports:
      - 9090:9090
    working_dir: /home

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
